import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import morgan from 'morgan';
import cookieParser from 'cookie-parser';
import path from 'path';
import { fileURLToPath } from 'url';
import auth from './routes/auth.js';
import messages from './routes/messages.js';
import contacts from './routes/contacts.js';
import inbound from './routes/inbound.js';
import attachments from './routes/attachments.js';
import { initDb, healthCheck } from './services/db.js';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();
app.disable('x-powered-by');
app.use(helmet({contentSecurityPolicy:false}));
app.use(morgan('combined'));
app.use(cookieParser());
app.use(express.json({limit:'15mb'}));
app.use(express.urlencoded({extended:true,limit:'15mb'}));
app.get('/health',async(req,res)=>{try{await healthCheck();res.json({ok:true,service:'rebotics-webmail'});}catch(e){res.status(503).json({ok:false,error:'database unavailable'});}});
app.use('/api/auth',auth);
app.use('/api/messages',messages);
app.use('/api/contacts',contacts);
app.use('/api/inbound',inbound);
app.use('/api/attachments',attachments);
app.use(express.static(path.join(__dirname,'public'),{extensions:['html']}));
app.use((req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const port=Number(process.env.PORT||8080);
await initDb();
app.listen(port,()=>console.log(`Rebotics Mail listening on ${port}`));
